apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairos-api-dev
  labels:
    App: FairosApiDev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      App: FairosApiDev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: app-vault-reader
        vault.hashicorp.com/agent-inject-secret-config: secrets/fairos-api/dev/app
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secrets/fairos-api/dev/app" -}}
          echo "sourcing";
          export FUJI_SERVER_URL={{ .Data.FUJI_SERVER_URL }}
          export DPID_API_URL={{ .Data.DPID_API_URL }}
          {{- end -}}
      labels:
        App: FairosApiDev
    spec:
      containers:
        - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/fairos-api-dev:latest
          name: fairos-api-dev
          command: ['/bin/bash', '-c']
          args:
            - echo "SOURCING ENV"; source /vault/secrets/config; uvicorn fairos_api:app --host 0.0.0.0 --port 8000;
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: '0.5'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      serviceAccountName: 'vault-auth'
